# Copyright 2026 Akretion (https://www.akretion.com).
# @author Raphaël Valyi <raphael.valyi@akretion.com>
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

from odoo import Command, _, fields, models
from odoo.exceptions import UserError


class BillToPickingWizard(models.TransientModel):
    _name = "bill.to.picking.wizard"
    _description = "Wizard to add bill lines to Picking"

    picking_id = fields.Many2one(
        "stock.picking",
        string="Existing Picking",
        domain=(
            "[('partner_id', '=', partner_id), ('state', 'not in', ['done', 'cancel']),"
            " ('picking_type_code', '=', 'incoming')]"
        ),
    )
    partner_id = fields.Many2one("res.partner", string="Vendor", required=True)

    auto_validate = fields.Boolean(
        string="Auto-Validate Receipt",
        default=lambda self: self.env.company.auto_validate_matched_picking,
    )

    def _get_active_lines(self):
        active_ids = self.env.context.get("active_ids", [])
        return self.env["picking.bill.line.match"].browse(active_ids)

    def _get_bills(self):
        """Vendor bill(s) whose lines this wizard is fed with."""
        return self._get_active_lines().aml_id.move_id

    def _get_bill_label(self, bill):
        """Label of a bill, tolerating a still nameless draft.

        The bill of an imported document is usually matched before being
        posted, and a draft ``account.move`` is named ``"/"``: using that as
        the origin would be worse than nothing. The display name (which
        identifies the draft) is used in that case.
        """
        if bill.name and bill.name != "/":
            return bill.name
        return bill.display_name

    def _get_origin(self):
        """Origin of the picking this wizard generates.

        The receipt is created from vendor bill lines, so the bill is its
        origin, and the marker says it did not come from a supplier document
        typed by the warehouse but from the bill matching: a receipt that
        appears in stock without anyone creating it must explain itself.
        """
        labels = [self._get_bill_label(bill) for bill in self._get_bills()]
        if not labels:
            return False
        return _("%(bills)s (bill matching)", bills=", ".join(labels))

    def _post_bill_matching_message(self, generated, aml_lines):
        """Trace, on the receipt, where it comes from and why it exists.

        The receipt is either generated by the matching or fed with bill
        lines; in both cases the traceability belongs to the receipt, with a
        link back to the vendor bill, so an accountant can go from the stock
        document to the bill that produced it.
        """
        bills = aml_lines.move_id
        if not bills:
            return
        bill_links = ", ".join(bill._get_html_link() for bill in bills)
        if generated:
            body = _(
                "This receipt was created by the bill matching wizard from "
                "%(bills)s with %(line_count)s line(s).",
                bills=bill_links,
                line_count=len(aml_lines),
            )
            if self.env.context.get("bill_matching_auto_create"):
                body += " " + _(
                    "No open receipt nor purchase order existed for this "
                    "vendor, so the bill generated it automatically."
                )
            body += " " + (
                _("It was validated automatically.")
                if self.auto_validate
                else _("It is waiting to be received.")
            )
        else:
            body = _(
                "The bill matching wizard added %(line_count)s line(s) from "
                "%(bills)s to this receipt.",
                bills=bill_links,
                line_count=len(aml_lines),
            )
        self.picking_id.message_post(body=body)

    def action_add_to_picking(self):
        self.ensure_one()
        lines = self._get_active_lines()
        aml_ids = lines.aml_id.filtered(
            lambda l: l.product_id and l.product_id.type in ("product", "consu")
        )

        if not aml_ids:
            raise UserError(_("No bill lines with products were selected."))

        # Whether this wizard generates the receipt or feeds an existing one
        # decides both the auto-validation and the origin: it used to be
        # guessed from ``picking.origin`` being empty, which is wrong as soon
        # as the origin is used for what it is meant to be (the source
        # document).
        generated = not self.picking_id
        if generated:
            company = aml_ids[0].company_id
            picking_type = self.env["stock.picking.type"].search(
                [
                    ("code", "=", "incoming"),
                    ("company_id", "=", company.id),
                ],
                limit=1,
            )

            self.picking_id = self.env["stock.picking"].create(
                {
                    "company_id": company.id,
                    "picking_type_id": picking_type.id,
                    "partner_id": self.partner_id.id,
                    "origin": self._get_origin(),
                    "location_id": picking_type.default_location_src_id.id
                    or self.env.ref("stock.stock_location_suppliers").id,
                    "location_dest_id": picking_type.default_location_dest_id.id,
                    "move_type": "direct",  # avoid conflict with ctx default_move_type
                }
            )

        for aml in aml_ids:
            move_vals = {
                "name": aml.name or aml.product_id.display_name,
                "product_id": aml.product_id.id,
                "product_uom_qty": aml.unmatched_qty,
                "picking_id": self.picking_id.id,
                "location_id": self.picking_id.location_id.id,
                "location_dest_id": self.picking_id.location_dest_id.id,
                "invoice_line_ids": [Command.link(aml.id)],
                "product_uom": aml.product_uom_id.id,
            }
            # Set quantity_done if auto-validating
            if self.auto_validate and generated:
                move_vals["quantity_done"] = aml.unmatched_qty

            self.env["stock.move"].create(move_vals)

        if self.picking_id.state == "draft":
            self.picking_id.action_confirm()

        # Auto Validate the receipt this wizard just generated, or simply
        # assign an existing one (which is never validated behind the user's
        # back)
        if self.auto_validate and generated:
            self.picking_id.button_validate()
        else:
            self.picking_id.action_assign()

        self._post_bill_matching_message(generated, aml_ids)

        action = self.env["ir.actions.actions"]._for_xml_id(
            "stock.action_picking_tree_all"
        )
        action.update(
            {
                "view_mode": "form",
                "res_id": self.picking_id.id,
                "views": [[self.env.ref("stock.view_picking_form").id, "form"]],
            }
        )
        return action
