# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.14.2
_src_path: gh:oca/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_version: 14.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups:
- product_expiry_simple
- stock_mass_scrap,stock_move_quick_lot
repo_description: Odoo Stock, Workflow and Organization
repo_name: stock-logistics-workflow
repo_slug: stock-logistics-workflow
repo_website: https://github.com/OCA/stock-logistics-workflow
travis_apt_packages: []
travis_apt_sources: []

