# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.17.1
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 13.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups:
- procurement_auto_create_group_carrier,stock_picking_group_by_partner_by_carrier,stock_picking_group_by_partner_by_carrier_by_date
repo_description: This project aims to deal with modules related to manage logistic
    flows.
repo_name: Odoo Stock Logistic Workflow
repo_slug: stock-logistics-workflow
repo_website: https://github.com/OCA/stock-logistics-workflow
travis_apt_packages: []
travis_apt_sources: []

