from . import procurement_group
from . import res_partner
from . import sale_order_line
from . import sale_order
from . import stock_move
from . import stock_picking
from . import stock_picking_type
from . import stock_rule
from . import stock_warehouse
