# Copyright 2026 Akretion (https://www.akretion.com).
# @author Raphaël Valyi <raphael.valyi@akretion.com>
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

from collections import defaultdict

from odoo import Command, _, api, fields, models
from odoo.exceptions import UserError

_logger = __import__("logging").getLogger(__name__)

MATCHING_PRECISION = 0.001
MATCHING_EPSILON_SQL = 0.0001
INVOICE_STATE_INVOICED = "invoiced"
INVOICE_STATE_2B_INVOICED = "2binvoiced"


class PickingBillLineMatch(models.Model):
    _name = "picking.bill.line.match"
    _description = "Stock Move and Vendor Bill line matching view"
    _auto = False

    # STRICT ORDERING:
    # Matched vs Unmatched -> Product -> pairing group -> Vendor Bill vs Receipt
    #
    # Inside a product group the lines are ordered by their pairing rank, so a
    # vendor bill line is immediately followed by the receipt lines carrying
    # the same Match Ref; the lines that could not be paired (a bill line
    # without reference, a receipt whose reference no bill line carries) have
    # no rank and come last (PostgreSQL sorts NULLs last on ASC), bills still
    # before receipts. Within a group, vendor bills come first, then the
    # receipts, each ordered by id so the screen is stable.
    _order = (
        "is_matched ASC, product_id, pair_rank ASC, line_type DESC,"
        " is_done DESC, aml_id, sm_id"
    )

    sm_id = fields.Many2one(comodel_name="stock.move", readonly=True)
    aml_id = fields.Many2one(comodel_name="account.move.line", readonly=True)

    company_id = fields.Many2one(comodel_name="res.company", readonly=True)
    partner_id = fields.Many2one(comodel_name="res.partner", readonly=True)
    product_id = fields.Many2one(comodel_name="product.product", readonly=True)

    line_qty = fields.Float("Initial Qty", readonly=True)
    unmatched_qty = fields.Float(readonly=True)
    is_matched = fields.Boolean(readonly=True)
    is_done = fields.Boolean("Is Done/Posted", readonly=True)
    line_type = fields.Selection(
        [("stock_move", "Receipt"), ("vendor_bill", "Vendor Bill")],
        string="Type",
        readonly=True,
    )

    line_uom_id = fields.Many2one(comodel_name="uom.uom", string="UoM", readonly=True)
    picking_id = fields.Many2one(comodel_name="stock.picking", readonly=True)
    account_move_id = fields.Many2one(comodel_name="account.move", readonly=True)

    line_amount_untaxed = fields.Monetary(readonly=True)
    currency_id = fields.Many2one(comodel_name="res.currency", readonly=True)
    state = fields.Char(readonly=True)
    reference = fields.Char(compute="_compute_reference")

    matched_reference = fields.Char("Matched To", compute="_compute_matched_reference")

    # Generic Field for Duck-Typed SQL Grouping
    matching_reference = fields.Char(
        "Match Ref.",
        readonly=True,
        help="Reference of the source line this line reconciles on — normally "
        "the purchase order line (in Brazil, the xPed/nItemPed pair of the "
        "NFe; otherwise the canonical key generated by the document import). "
        "It identifies the ORDER "
        "LINE, not the shipment: an order line received in several deliveries "
        "legitimately carries the same reference on each of them, and they "
        "stay grouped together in this screen.",
    )

    pair_rank = fields.Integer(
        readonly=True,
        help="Rank of the pairing group inside the product group: the vendor "
        "bill lines and the receipt lines sharing the same reference get the "
        "same rank, so a bill line is followed by its own receipts. Empty "
        "(the line could not be paired) sorts last.",
    )

    @api.depends("picking_id.name", "account_move_id.name")
    def _compute_reference(self):
        for line in self:
            if line.picking_id:
                line.reference = line.picking_id.name
                if line.picking_id.origin:
                    line.reference += f" ({line.picking_id.origin})"
            elif line.account_move_id:
                line.reference = line.account_move_id.name
                if line.account_move_id.invoice_origin:
                    line.reference += f" ({line.account_move_id.invoice_origin})"

    @api.depends(
        "aml_id.move_line_ids.picking_id.name", "sm_id.invoice_line_ids.move_id.name"
    )
    def _compute_matched_reference(self):
        for rec in self:
            if rec.aml_id:
                rec.matched_reference = ", ".join(
                    rec.aml_id.move_line_ids.mapped("picking_id.name")
                )
            elif rec.sm_id:
                rec.matched_reference = ", ".join(
                    rec.sm_id.invoice_line_ids.mapped("move_id.name")
                )
            else:
                rec.matched_reference = ""

    @api.model
    def _get_duck_typed_sql_ref(self, model_name, alias):
        """SQL expression of the matching reference for a given table alias.

        A module that knows where the reference comes from (a localization,
        typically) provides ``_get_bill_matching_reference_sql(alias)``; the
        hook is duck-typed, so this module keeps no dependency on it. Its
        derivation takes precedence, and the STORED ``matching_reference``
        field is the fallback: the pairing stays usable — and testable —
        without any localization, and an explicitly stored reference still
        counts when the derivation has nothing to say.
        """
        stored_ref = f"{alias}.matching_reference"
        model = self.env[model_name]
        if not hasattr(model, "_get_bill_matching_reference_sql"):
            return stored_ref
        derived_ref = model._get_bill_matching_reference_sql(alias)
        return f"COALESCE(NULLIF({derived_ref}, ''), {stored_ref})"

    @api.model
    def _bill_pair_rank_sql(self, alias="aml"):
        """Rank of a VENDOR BILL line inside its product group.

        Lines of a product group sharing the same reference get the same
        rank, which lets the screen show a vendor bill line immediately
        followed by the receipt lines carrying its reference:
        ``_order`` sorts by (product, pair_rank, line_type DESC, ...), so the
        bill line comes first and its receipts right after it. The groups
        themselves are ordered by reference value.

        A line whose reference no bill line of the product carries — no
        reference at all, or a reference only receipts know about — gets NULL,
        which PostgreSQL sorts last: the lines that could not be paired end up
        at the bottom of the product group (bills before receipts, thanks to
        ``line_type DESC``).
        """
        ref_self = self._get_duck_typed_sql_ref("account.move.line", alias)
        ref_rank = self._get_duck_typed_sql_ref("account.move.line", "aml_rank")
        return f"""CASE WHEN {ref_self} > '' THEN CAST((
                    SELECT COUNT(DISTINCT {ref_rank})
                    FROM account_move_line aml_rank
                    JOIN account_move am_rank ON am_rank.id = aml_rank.move_id
                    WHERE am_rank.move_type IN ('in_invoice', 'in_refund')
                      AND am_rank.state IN ('draft', 'posted')
                      AND aml_rank.display_type = 'product'
                      AND aml_rank.company_id = {alias}.company_id
                      AND aml_rank.product_id = {alias}.product_id
                      AND {ref_rank} > ''
                      AND {ref_rank} < {ref_self}
                ) AS int) END"""

    @api.model
    def _receipt_pair_rank_sql(self, alias="sm"):
        """Rank of a RECEIPT line inside its product group.

        Same rank as the bill line carrying the same reference — but only when
        such a bill line exists: a receipt whose reference no bill line of the
        product carries is NOT paired and gets NULL, to be sorted at the end of
        the product group.
        """
        ref_self = self._get_duck_typed_sql_ref("stock.move", alias)
        ref_check = self._get_duck_typed_sql_ref("account.move.line", "aml_check")
        ref_rank = self._get_duck_typed_sql_ref("account.move.line", "aml_rank")
        return f"""CASE WHEN {ref_self} > '' AND EXISTS (
                    SELECT 1
                    FROM account_move_line aml_check
                    JOIN account_move am_check ON am_check.id = aml_check.move_id
                    WHERE am_check.move_type IN ('in_invoice', 'in_refund')
                      AND am_check.state IN ('draft', 'posted')
                      AND aml_check.display_type = 'product'
                      AND aml_check.company_id = {alias}.company_id
                      AND aml_check.product_id = {alias}.product_id
                      AND {ref_check} = {ref_self}
                ) THEN CAST((
                    SELECT COUNT(DISTINCT {ref_rank})
                    FROM account_move_line aml_rank
                    JOIN account_move am_rank ON am_rank.id = aml_rank.move_id
                    WHERE am_rank.move_type IN ('in_invoice', 'in_refund')
                      AND am_rank.state IN ('draft', 'posted')
                      AND aml_rank.display_type = 'product'
                      AND aml_rank.company_id = {alias}.company_id
                      AND aml_rank.product_id = {alias}.product_id
                      AND {ref_rank} > ''
                      AND {ref_rank} < {ref_self}
                ) AS int) END"""

    @api.model
    def _select_sm_line(self):
        ref_sql = self._get_duck_typed_sql_ref("stock.move", "sm")
        pair_rank_sql = self._receipt_pair_rank_sql("sm")
        return f"""
            SELECT
                sm.id,
                sm.company_id,
                sp.partner_id,
                sm.product_id,
                sp.state,
                NULL AS currency_id,
                sm.product_uom_qty AS line_qty,
                sm.unmatched_qty AS unmatched_qty,
                (sm.product_uom_qty - COALESCE(sm.unmatched_qty, 0.0))
                    > {MATCHING_EPSILON_SQL} AS is_matched,
                sp.state = 'done' AS is_done,
                'stock_move' AS line_type,
                sm.product_uom AS line_uom_id,
                0 AS line_amount_untaxed,
                sm.id as sm_id,
                NULL as aml_id,
                sm.picking_id as picking_id,
                NULL as account_move_id,
                {ref_sql} AS matching_reference,
                {pair_rank_sql} AS pair_rank
            FROM
                stock_move sm
            JOIN
                stock_picking sp ON sm.picking_id = sp.id
            JOIN
                stock_picking_type pt ON sp.picking_type_id = pt.id
            JOIN
                product_product pp ON sm.product_id = pp.id
            JOIN
                product_template prod_tmpl ON pp.product_tmpl_id = prod_tmpl.id
            WHERE
                pt.code in ('incoming', 'outgoing')
                AND sm.state != 'cancel'
                AND prod_tmpl.type in ('product', 'consu')
        """

    @api.model
    def _select_am_line(self):
        ref_sql = self._get_duck_typed_sql_ref("account.move.line", "aml")
        pair_rank_sql = self._bill_pair_rank_sql("aml")
        return f"""
            SELECT
                -aml.id as id,
                aml.company_id,
                aml.partner_id,
                aml.product_id,
                am.state,
                aml.currency_id,
                aml.quantity AS line_qty,
                aml.unmatched_qty AS unmatched_qty,
                (aml.quantity - COALESCE(aml.unmatched_qty, 0.0))
                    > {MATCHING_EPSILON_SQL} AS is_matched,
                am.state = 'posted' AS is_done,
                'vendor_bill' AS line_type,
                aml.product_uom_id AS line_uom_id,
                aml.price_subtotal AS line_amount_untaxed,
                NULL as sm_id,
                aml.id as aml_id,
                NULL as picking_id,
                aml.move_id as account_move_id,
                {ref_sql} AS matching_reference,
                {pair_rank_sql} AS pair_rank
            FROM
                account_move_line aml
            JOIN
                account_move am ON aml.move_id = am.id
            JOIN
                product_product pp ON aml.product_id = pp.id
            JOIN
                product_template prod_tmpl ON pp.product_tmpl_id = prod_tmpl.id
            WHERE
                aml.display_type = 'product'
                AND am.move_type in ('in_invoice', 'in_refund')
                AND am.state in ('draft', 'posted')
                AND prod_tmpl.type in ('product', 'consu')
        """

    @property
    def _table_query(self):
        return "(%s) UNION ALL (%s)" % (self._select_sm_line(), self._select_am_line())

    def action_open_line(self):
        self.ensure_one()
        return {
            "type": "ir.actions.act_window",
            "res_model": "account.move" if self.account_move_id else "stock.picking",
            "view_mode": "form",
            "target": "new",
            "res_id": self.account_move_id.id
            if self.account_move_id
            else self.picking_id.id,
        }

    def action_unmatch_lines(self):
        """DEBUG/UNDO: Easily sever the M2M links of selected lines."""

        affected_moves = self.env["stock.move"]
        for record in self:
            if record.aml_id:
                affected_moves |= record.aml_id.move_line_ids
                record.aml_id.write({"move_line_ids": [Command.clear()]})
            elif record.sm_id:
                affected_moves |= record.sm_id
                amls = self.env["account.move.line"].search(
                    [("move_line_ids", "in", record.sm_id.id)]
                )
                for aml in amls:
                    aml.write({"move_line_ids": [Command.unlink(record.sm_id.id)]})

        # Flush M2M changes to DB so unmatched_qty recomputes properly
        self.env.flush_all()

        # Duck Typing integration with the `stock_picking_invoicing` module:
        if hasattr(self.env["stock.move"], "invoice_state"):
            for move in affected_moves:
                move.invoice_state = (
                    INVOICE_STATE_INVOICED
                    if move.unmatched_qty <= MATCHING_PRECISION
                    else INVOICE_STATE_2B_INVOICED
                )
            for picking in affected_moves.mapped("picking_id"):
                picking.invoice_state = (
                    INVOICE_STATE_INVOICED
                    if all(
                        m.invoice_state == INVOICE_STATE_INVOICED
                        for m in picking.move_ids
                    )
                    else INVOICE_STATE_2B_INVOICED
                )

    @api.model
    def _get_matching_pairs(self, aml_lines, sm_lines):
        """
        Groups by (Product + matching_reference).
        If a localization/ext extension is installed (for instance l10n_br, the
        Brazilian localization, where the reference comes from the NFe
        xPed/nItemPed pair), this will magically group by (Product + reference).
        Otherwise, it seamlessly groups just by Product!

        An empty/NULL reference means "unspecified" and acts as a WILDCARD:
        it matches any receipt line of the same product. This keeps the
        product-only matching working when one side carries no reference —
        e.g. bills imported before the reference existed, or installations
        where the localization fills the bill side but the stock side hook
        is not installed. Exact reference matches are returned first so the
        quantity distribution in action_match_lines consumes them before the
        wildcard candidates.
        """
        matches = []
        aml_by_key = defaultdict(lambda: self.env["account.move.line"])
        for line in aml_lines:
            key = (line.product_id, line.matching_reference or False)
            aml_by_key[key] |= line

        sm_by_key = defaultdict(lambda: self.env["stock.move"])
        for line in sm_lines:
            key = (line.product_id, line.matching_reference or False)
            sm_by_key[key] |= line

        for (product, ref), amls in aml_by_key.items():
            if ref:
                # exact reference first, then receipts with no reference
                stock_moves_to_link = sm_by_key.get(
                    (product, ref), self.env["stock.move"]
                ) | sm_by_key.get((product, False), self.env["stock.move"])
            else:
                # no reference on the bill line: any receipt of the product
                stock_moves_to_link = self.env["stock.move"]
                for (sm_product, _sm_ref), sm_group in sm_by_key.items():
                    if sm_product == product:
                        stock_moves_to_link |= sm_group
            if stock_moves_to_link:
                for aml in amls:
                    matches.append((aml, stock_moves_to_link))
        return matches

    def _match_one_aml(self, aml, stock_moves_to_link):
        """Consume receipt lines for a single bill line.

        Returns ``(consumed, to_receive, quantities)``:

        * ``consumed``: the receipt lines the bill line actually consumes
          (plus the ones another line already consumed, added by the caller);
        * ``to_receive``: the pending receipt lines whose reception must be
          driven by this matching;
        * ``quantities``: the quantity to set as done per pending receipt
          line — accumulated, since several bill lines may consume the same
          receipt line and the receipt must not be validated short of what is
          being billed.
        """
        remaining_to_match = aml.unmatched_qty
        consumed = self.env["stock.move"]
        to_receive = self.env["stock.move"]
        quantities = {}
        for move in stock_moves_to_link:
            if remaining_to_match <= MATCHING_PRECISION:
                break
            if move.state == "done":
                # already received: only its billing capacity is left
                available_qty = move.unmatched_qty
                drive_reception = False
            elif move.state in ("draft", "confirmed", "assigned"):
                # pending receipt: the quantity left to receive
                available_qty = move.product_uom_qty - move.quantity_done
                drive_reception = True
            else:
                continue
            qty_to_do = min(remaining_to_match, available_qty)
            if qty_to_do <= MATCHING_PRECISION:
                continue
            remaining_to_match -= qty_to_do
            consumed |= move
            if drive_reception:
                to_receive |= move
                quantities[move] = quantities.get(move, 0.0) + qty_to_do
        return consumed, to_receive, quantities

    def action_match_lines(self):
        if not self.sm_id and not self.aml_id:
            raise UserError(
                _("You must select at least one line to perform an action!")
            )

        if len(self.account_move_id) > 1:
            raise UserError(
                _("You cannot match lines from multiple Vendor Bills at once!")
            )

        pairs = self._get_matching_pairs(self.aml_id, self.sm_id)

        moves_to_receive = self.env["stock.move"]
        all_matched_moves = self.env["stock.move"]
        qty_to_set = {}

        for aml, stock_moves_to_link in pairs:
            consumed, to_receive, quantities = self._match_one_aml(
                aml, stock_moves_to_link
            )

            # 1. Establish the M2M links. Only link the moves this bill line
            # actually consumes (plus those it was already linked to):
            # linking the whole candidate group would make unmatched_qty go
            # negative (quantity minus the SUM of every linked move's qty)
            # and pollute later rounds.
            consumed |= aml.move_line_ids & stock_moves_to_link
            aml.move_line_ids = [Command.link(sm.id) for sm in consumed]

            moves_to_receive |= to_receive
            for move, qty in quantities.items():
                qty_to_set[move] = qty_to_set.get(move, 0.0) + qty

            all_matched_moves |= stock_moves_to_link

        # 2. Safely Process and Automate Receptions
        if moves_to_receive:
            pickings_to_process = moves_to_receive.mapped("picking_id")

            for picking in pickings_to_process:
                if picking.state == "draft":
                    picking.action_confirm()
                if picking.state not in ("assigned", "done"):
                    picking.action_assign()

            # Safely set the quantity done for what we are currently matching
            for move, qty in qty_to_set.items():
                move.quantity_done += qty

            # _action_done safely finalizes the moves and automatically creates
            # a backorder for anything not matched!
            pickings_to_process.with_context(cancel_backorder=False)._action_done()

        # Flush M2M changes to DB so unmatched_qty recomputes properly
        self.env.flush_all()

        # 3. Duck Typing integration with `stock_picking_invoicing`
        if hasattr(self.env["stock.move"], "invoice_state"):
            for move in all_matched_moves:
                move.invoice_state = (
                    INVOICE_STATE_INVOICED
                    if move.unmatched_qty <= MATCHING_PRECISION
                    else INVOICE_STATE_2B_INVOICED
                )
            for picking in all_matched_moves.mapped("picking_id"):
                picking.invoice_state = (
                    INVOICE_STATE_INVOICED
                    if all(
                        m.invoice_state == INVOICE_STATE_INVOICED
                        for m in picking.move_ids
                    )
                    else INVOICE_STATE_2B_INVOICED
                )

    def action_add_to_picking(self):
        records = self
        if not records:
            move_id = self.env.context.get("default_account_move_id")
            if move_id:
                records = self.search(
                    [
                        ("account_move_id", "=", move_id),
                        ("unmatched_qty", ">", MATCHING_PRECISION),
                    ]
                )

        if not records or not records.aml_id:
            raise UserError(_("No Vendor Bill lines found to add to a Picking."))

        return {
            "type": "ir.actions.act_window",
            "name": _("Create / Add to Picking"),
            "res_model": "bill.to.picking.wizard",
            "target": "new",
            "view_mode": "form",
            "context": {
                "default_partner_id": records[0].partner_id.id,
                "dialog_size": "medium",
                "active_model": "picking.bill.line.match",
                "active_ids": records.ids,
            },
        }
