from . import product
from . import res_partner
from . import sale_order
from . import sale_order_line
from . import stock_move
from . import stock_picking
from . import stock_picking_type
from . import stock_quant
from . import stock_warehouse
from . import stock_rule
